### ISSUE TITLE
save the changes?

### ISSUE THREAD

**Issue by samspo** [Leftium/todo.html#1]
Hi,

Nice. Works well but doesn't save anything my todo.html file. Is there anything I missed?
My todotxt is installed with homebrew following these instructions: http://dangerisgo.com/blog/2012/09/20/setup-todo-dot-txt-cli-on-osx-with-homebrew-and-dropbox/ 

Thank you,

**Comment by Leftium** [comment]
1. You're running OS X, a platform that does not allow todo.html to write to the local file system. Currently, the only supported platform that allows writing to files is Internet Explorer. The other browsers no longer allow the JavaScript techniques used to write to the local file system (due to security concerns). 
2. I don't think I ever got to supporting external todo.txt files. The todo data is stored in the todo.html file _itself_.

_Blame draconian browser security, but I've almost given up the dream of writing a portable todo.html..._

**Comment by samspo** [comment]
Thanks for this quick answer!
